### ISSUE TITLE
Compile new Caffe library and classification via CK

### ISSUE THREAD

**Issue by DVEfremov** [ctuning/ck-crowd-scenarios#1]
Now are used pre-compilled  libcaffe.so per CPU architecture (now only 2 versions):
`CK/ck-crowd-scenarios/experiment.scenario.mobile/bvlc-caffenet-android-recognize-image/code/0ef2b70e4791b83b/arm64-v8a/libcaffe.so
`
It's required to add libs and classification programm compiled using ck as follows:
$ck compile program:caffe-classification --speed

for all caffe scenarios 
* bvlc-alexnet-android-recognize-image
* bvlc-caffenet-android-recognize-image
* bvlc-googlenet-android-recognize-image
* deepscale-squeezenet-1.0-android-recognize-image
* deepscale-squeezenet-1.1-android-recognize-image

Also 2 version of Caffe should be available:
* based on branch master 
* based on branch opencl

**Comment by gfursin** [comment]
I also fixed Caffe compilation for Android 32 bit ARM via CK. It is possible to check it via:
 $ ck install package:lib-caffe-bvlc-master-cpu-android --target_os=android21-arm-v7a
So, now we can compile Caffe for both 32-bit and 64-bit ARM Android. BTW, we could probably compile it even for Android 19 API (to support Android V4.x to cover more distinct hardware), but compilation of one of the libs fail :( ...

I also created dummy repo:
* https://github.com/ctuning/ck-crowd-scenarios-arc
where we will store previous libcaffe/classification versions participated in crowd-tuning (to keep them for reproducibility/comparison) ...

**Comment by DVEfremov** [comment]
Looks like need to handle pulling compiled libs and programs at:
`CK/ck-crowdtuning/module/experiment.scenario.mobile/module.py (121 -124)`

**Comment by gfursin** [comment]
The function 'get' from the 'experiment.scenario.mobile' is called when you press Update on Android app. It prepares JSON with all scenarios supported by your mobile, as well as full URLs which then Android app uses to download scenarios ...

**Comment by gfursin** [comment]
We now have new scenarios, so if we have more issues, let's open a new ticket! Thanks!
