### ISSUE TITLE
Add scenario for android app based on tensorflow

### ISSUE THREAD

**Issue by DVEfremov** [ctuning/ck-crowd-scenarios#2]
Build tensorflow libs and program for android based on 
* ck-tensorflow
* CK/ck-caffe/module/experiment.bench.caffe.mobile/module.py

and add scenario to ck-crowd-scenarios repository 

Tensorflow libs should be updated like for caffe-based scenarios with command 
* $ ck generate experiment.bench.caffe.mobile
* $ ck process experiment.scenario.mobile

Then it should be available at android app after applying "Update scenarios"

**Comment by DVEfremov** [comment]
I've tried to build current tensorflow-classification program for andoird:
* $ ck compile program:caffe-classification --target_os=android21-arm64
complete without error 

but if run it 
* $ ck run program:tensorflow-classification --target_os=android21-arm64
got error 

```
7 KB/s (386 bytes in 0.048s)
Traceback (most recent call last):
  File "/home/daniil/Projects/Dividiti/ck/ck/kernel.py", line 9090, in <module>
    r=access(sys.argv[1:])
  File "/home/daniil/Projects/Dividiti/ck/ck/kernel.py", line 9048, in access
    rr=perform_action(i)
  File "/home/daniil/Projects/Dividiti/ck/ck/kernel.py", line 3274, in perform_action
    return a(i)
  File "/home/daniil/CK/ck-autotuning/module/program/module.py", line 2745, in run
    return process(i)
  File "/home/daniil/CK/ck-autotuning/module/program/module.py", line 168, in process
    r=process_in_dir(ii)
  File "/home/daniil/CK/ck-autotuning/module/program/module.py", line 2270, in process_in_dir
    if rs.endswith('"'):
UnboundLocalError: local variable 'rs' referenced before assignment


```

**Comment by DVEfremov** [comment]
I've found generate pushed script at android:

```
shell@trelte:/ $ cat /data/local/tmp/tmp/tmp-8NpduI.sh
export PATH=/data/local/tmp/tools:$PATH; export LD_LIBRARY_PATH=.:/data/local/tmp:/data/local/tmp/lib:$LD_LIBRARY_PATH

export CK_DATASET_PATH=/home/daniil/CK/ctuning-datasets-min/dataset/image-jpeg-0001/

export CK_DATASET_FILENAME=data.jpg

echo    executing code ...
 ${CK_ENV_COMPILER_PYTHON_FILE} ../classify_image.py --model_dir=${CK_ENV_MODEL_TENSORFLOW} --image_file=data.jpg
```
Look like we need write c++ tensorflow classification wrapper program

**Comment by gfursin** [comment]
As I mentioned before, Caffe, TensorFlow and other large apps are not yet working properly on Android via CK - I am working on it. However, if CK-Caffe is mostly ready (CK generates binaries and all deps for Android), then TensorFlow classification is just a call to python module, so you will not be able to run it on Android. Instead, you need to find TensorFlow demo for Android (on TensorFlow GitHub), then check how it compiles and works, and then add it as package to CK (similar to lib-caffe-bvlc-master-cpu) and then compilation of classificaiton to binary via CK (similar to program:caffe-classification-android) ...

If something is unclear, I can help. So, the first step is to convert TensorFlow Android demo compilation to CK workflow ...

**Comment by gfursin** [comment]
By the way, I think I fixed "local variable 'rs' referenced before assignment" error - it's orthogonal to TensorFlow ... Do you mind to update all repos and just to try to run it again and just see that this error will dissapear (TensorFlow will still not work though) ... Thanks!

**Comment by gfursin** [comment]
Today, I unified compilation of TensorFlow for Linux and Android via CK and added scenario here (with Inception/GoogleNet model). It works on my Samsung S7 mobile and sends timing to the repo, but there is an issue on Android app with parsing of output (probabilities and text). i.e. I get the following:
![screenshot_20170328-233230](https://cloud.githubusercontent.com/assets/7384805/24428486/ee18816c-140e-11e7-9960-bd9e4e4ea967.png)
I don't know if the problem is in the Android app or in the classification - @DVEfremov , do you mind to check it, please? Thanks a lot!

**Comment by DVEfremov** [comment]
Fixed. Merged. 
Closing.
